/* MoonWorks - Game Development Framework
 * Copyright 2021 Evan Hemsley
 */

/* Derived from code by Ethan Lee (Copyright 2009-2021).
 * Released under the Microsoft Public License.
 * See fna.LICENSE for details.

 * Derived from code by the Mono.Xna Team (Copyright 2006).
 * Released under the MIT License. See monoxna.LICENSE for details.
 */

using System;
using System.Runtime.CompilerServices;
using System.Text;
using System.Numerics;
using System.Runtime.InteropServices;

namespace MoonWorks.Graphics;

/// <summary>
/// Describes a 32-bit packed color.
/// </summary>
public record struct Color(byte R, byte G, byte B, byte A = 255)
{
	public Color(int r, int g, int b, int a = 255) : this(
		(byte) int.Clamp(r, 0, 255),
		(byte) int.Clamp(g, 0, 255),
		(byte) int.Clamp(b, 0, 255),
		(byte) int.Clamp(a, 0, 255)
	) { }

	/// <summary>
	/// Constructs an RGBA color from scalars which represent red, green, blue and alpha values.
	/// </summary>
	/// <param name="r">Red component value from 0.0f to 1.0f.</param>
	/// <param name="g">Green component value from 0.0f to 1.0f.</param>
	/// <param name="b">Blue component value from 0.0f to 1.0f.</param>
	/// <param name="alpha">Alpha component value from 0.0f to 1.0f.</param>
	public Color(float r, float g, float b, float a) : this(
		(byte) (System.Math.Clamp(r, 0, 1) * byte.MaxValue),
		(byte) (System.Math.Clamp(g, 0, 1) * byte.MaxValue),
		(byte) (System.Math.Clamp(b, 0, 1) * byte.MaxValue),
		(byte) (System.Math.Clamp(a, 0, 1) * byte.MaxValue)
	) { }

	/// <summary>
	/// Constructs an RGBA color from scalars which represent red, green, blue values. Alpha is assumed to be 1.
	/// </summary>
	/// <param name="r">Red component value from 0.0f to 1.0f.</param>
	/// <param name="g">Green component value from 0.0f to 1.0f.</param>
	/// <param name="b">Blue component value from 0.0f to 1.0f.</param>
	public Color(float r, float g, float b) : this(
		(byte) (System.Math.Clamp(r, 0, 1) * byte.MaxValue),
		(byte) (System.Math.Clamp(g, 0, 1) * byte.MaxValue),
		(byte) (System.Math.Clamp(b, 0, 1) * byte.MaxValue),
		(byte) 255
	) { }

	public Color(Vector4 vector) : this(vector.X, vector.Y, vector.Z, vector.W) { }

	/// <summary>
	/// Gets packed RGBA value of this <see cref="Color"/>.
	/// <para>NOTE: Because of endianness, if you format this value directly as a hex string, 
	/// the order of bytes may be wrong.</para>
	/// </summary>
	public readonly uint PackedValue() => Unsafe.BitCast<Color, uint>(this);

	/// <summary>
	/// Gets a <see cref="Color"/> representation for a packed RGBA value.
	/// <para>NEVER plug in a value that wasn't generated by PackedValue(),
	/// unless you're SURE you can deal with an endianness mismatch.</para>
	/// <para>Example: it's NOT safe to take 0xF0F8FFFF from AliceBlue and plug it into here!</para>
	/// </summary>
	public static Color FromPacked(uint rgba) => Unsafe.BitCast<uint, Color>(rgba);

	/// <summary>
	/// Gets a <see cref="Vector3"/> representation for this object.
	/// </summary>
	/// <returns>A <see cref="Vector3"/> representation for this object.</returns>
	public Vector3 ToVector3()
	{
		return new Vector3(R / 255.0f, G / 255.0f, B / 255.0f);
	}

	/// <summary>
	/// Gets a <see cref="Vector4"/> representation for this object.
	/// </summary>
	/// <returns>A <see cref="Vector4"/> representation for this object.</returns>
	public Vector4 ToVector4()
	{
		return new Vector4(R / 255.0f, G / 255.0f, B / 255.0f, A / 255.0f);
	}

	/// <summary>
	/// Performs linear interpolation of <see cref="Color"/>.
	/// </summary>
	/// <param name="value1">Source <see cref="Color"/>.</param>
	/// <param name="value2">Destination <see cref="Color"/>.</param>
	/// <param name="amount">Interpolation factor.</param>
	/// <returns>Interpolated <see cref="Color"/>.</returns>
	public static Color Lerp(Color value1, Color value2, float amount)
	{
		amount = float.Clamp(amount, 0.0f, 1.0f);
		return new Color(
			float.Lerp(value1.R / 255f, value2.R / 255f, amount),
			float.Lerp(value1.G / 255f, value2.G / 255f, amount),
			float.Lerp(value1.B / 255f, value2.B / 255f, amount),
			float.Lerp(value1.A / 255f, value2.A / 255f, amount)
		);
	}

	/// <summary>
	/// Translate a non-premultipled alpha <see cref="Color"/> to a <see cref="Color"/>
	/// that contains premultiplied alpha.
	/// </summary>
	/// <param name="vector">A <see cref="Vector4"/> representing color.</param>
	/// <returns>A <see cref="Color"/> which contains premultiplied alpha data.</returns>
	public static Color FromNonPremultiplied(System.Numerics.Vector4 vector)
	{
		return new Color(
			vector.X * vector.W,
			vector.Y * vector.W,
			vector.Z * vector.W,
			vector.W
		);
	}

	/// <summary>
	/// Translate a non-premultipled alpha <see cref="Color"/> to a <see cref="Color"/>
	/// that contains premultiplied alpha.
	/// </summary>
	/// <param name="r">Red component value.</param>
	/// <param name="g">Green component value.</param>
	/// <param name="b">Blue component value.</param>
	/// <param name="a">Alpha component value.</param>
	/// <returns>A <see cref="Color"/> which contains premultiplied alpha data.</returns>
	public static Color FromNonPremultiplied(byte r, byte g, byte b, byte a)
	{
		return new Color(
			r * a / 255,
			g * a / 255,
			b * a / 255,
			a
		);
	}

	// Modified from one of the responses here:
	// https://stackoverflow.com/questions/3018313/algorithm-to-convert-rgb-to-hsv-and-hsv-to-rgb-in-range-0-255-for-both/6930407#6930407
	public static Color FromHSV(float r, float g, float b)
	{
		r = (100 + r) % 1f;

		float hueSlice = 6 * r; // [0, 6)
		float hueSliceInteger = MathF.Floor(hueSlice);

		// In [0,1) for each hue slice
		float hueSliceInterpolant = hueSlice - hueSliceInteger;

		Vector3 tempRGB = new Vector3(
			b * (1f - g),
			b * (1f - g * hueSliceInterpolant),
			b * (1f - g * (1f - hueSliceInterpolant))
		);

		// The idea here to avoid conditions is to notice that the conversion code can be rewritten:
		//    if      ( var_i == 0 ) { R = V         ; G = TempRGB.z ; B = TempRGB.x }
		//    else if ( var_i == 2 ) { R = TempRGB.x ; G = V         ; B = TempRGB.z }
		//    else if ( var_i == 4 ) { R = TempRGB.z ; G = TempRGB.x ; B = V     }
		//
		//    else if ( var_i == 1 ) { R = TempRGB.y ; G = V         ; B = TempRGB.x }
		//    else if ( var_i == 3 ) { R = TempRGB.x ; G = TempRGB.y ; B = V     }
		//    else if ( var_i == 5 ) { R = V         ; G = TempRGB.x ; B = TempRGB.y }
		//
		// This shows several things:
		//  . A separation between even and odd slices
		//  . If slices (0,2,4) and (1,3,5) can be rewritten as basically being slices (0,1,2) then
		//      the operation simply amounts to performing a "rotate right" on the RGB components
		//  . The base value to rotate is either (V, B, R) for even slices or (G, V, R) for odd slices
		//
		float isOddSlice =  hueSliceInteger % 2f;                          // 0 if even (slices 0, 2, 4), 1 if odd (slices 1, 3, 5)
		float threeSliceSelector = 0.5f * (hueSliceInteger - isOddSlice);  // (0, 1, 2) corresponding to slices (0, 2, 4) and (1, 3, 5)

		Vector3 scrollingRGBForEvenSlices = new Vector3(b, tempRGB.Z, tempRGB.X); // (V, Temp Blue, Temp Red) for even slices (0, 2, 4)
		Vector3 scrollingRGBForOddSlices = new Vector3(tempRGB.Y, b, tempRGB.X);  // (Temp Green, V, Temp Red) for odd slices (1, 3, 5)
		Vector3 scrollingRGB = Vector3.Lerp(scrollingRGBForEvenSlices, scrollingRGBForOddSlices, isOddSlice);

		float IsNotFirstSlice = float.Clamp(threeSliceSelector, 0f, 1f);        // 1 if NOT the first slice (true for slices 1 and 2)
		float IsNotSecondSlice = float.Clamp(threeSliceSelector - 1f, 0f, 1f);  // 1 if NOT the first or second slice (true only for slice 2)

		Vector3 color = Vector3.Lerp(
			scrollingRGB,
			Vector3.Lerp(
				new Vector3(scrollingRGB.Z, scrollingRGB.X, scrollingRGB.Y),
				new Vector3(scrollingRGB.Y, scrollingRGB.Z, scrollingRGB.X),
				IsNotSecondSlice
			),
			IsNotFirstSlice
		);

		return new Color(color.X, color.Y, color.Z, 1f);
	}

	public static Color FromHSV(int r, int g, int b)
	{
		return FromHSV(r / 255f, g / 255f, b / 255f);
	}

	/// <summary>
	/// Multiply <see cref="Color"/> by value.
	/// </summary>
	/// <param name="value">Source <see cref="Color"/>.</param>
	/// <param name="scale">Multiplicator.</param>
	/// <returns>Multiplication result.</returns>
	public static Color operator *(Color value, float scale)
	{
		return new Color(
			value.R * scale / 255f,
			value.G * scale / 255f,
			value.B * scale / 255f,
			value.A * scale / 255f
		);
	}

	/// <summary>
	/// Returns a <see cref="String"/> representation of this <see cref="Color"/> in the format:
	/// {R:[red] G:[green] B:[blue] A:[alpha]}
	/// </summary>
	/// <returns><see cref="String"/> representation of this <see cref="Color"/>.</returns>
	public override string ToString()
	{
		StringBuilder sb = new StringBuilder(25);
		sb.Append("{R:");
		sb.Append(R);
		sb.Append(" G:");
		sb.Append(G);
		sb.Append(" B:");
		sb.Append(B);
		sb.Append(" A:");
		sb.Append(A);
		sb.Append("}");
		return sb.ToString();
	}

	/// <summary>
	/// Returns a hexadecimal <see cref="String"/> representation of this <see cref="Color"/> in the format:
	/// 0x[R][G][B][A]
	/// <para>Thus, it's in Big Endian format.</para>
	/// </summary>
	/// <returns><see cref="String"/> representation of this <see cref="Color"/>.</returns>
	public string ToHexString()
	{
		StringBuilder sb = new StringBuilder(10);
		sb.Append("#");
		sb.Append(R.ToString("X2"));
		sb.Append(G.ToString("X2"));
		sb.Append(B.ToString("X2"));
		sb.Append(A.ToString("X2"));
		return sb.ToString();
	}

	public static implicit operator VertexStructs.Ubyte4Norm(Color color) => new VertexStructs.Ubyte4Norm
	{
		X = color.R,
		Y = color.G,
		Z = color.B,
		W = color.A
	};

	public static implicit operator FColor(Color color) => new FColor
	{
		R = color.R / 255f,
		G = color.G / 255f,
		B = color.B / 255f,
		A = color.A / 255f
	};


#region Built-In Colors
	/// <summary>
	/// Transparent color (R:0, G:0, B:0, A:0).
	/// </summary>
	public static Color Transparent => new((byte)0, (byte)0, (byte)0, (byte)0);

	/// <summary>
	/// AliceBlue color (R:240, G:248, B:255, A:255).
	/// <para>RGBA Hex: #F0F8FFFF.</para>
	/// </summary>
	public static Color AliceBlue => new((byte)240, (byte)248, (byte)255);

	/// <summary>
	/// AntiqueWhite color (R:250, G:235, B:215, A:255).
	/// <para>RGBA Hex: #FAEBD7FF.</para>
	/// </summary>
	public static Color AntiqueWhite => new((byte)250, (byte)235, (byte)215);

	/// <summary>
	/// Aqua color (R:0, G:255, B:255, A:255).
	/// <para>RGBA Hex: #00FFFFFF.</para>
	/// </summary>
	public static Color Aqua => new((byte)0, (byte)255, (byte)255);

	/// <summary>
	/// Aquamarine color (R:127, G:255, B:212, A:255).
	/// <para>RGBA Hex: #7FFFD4FF.</para>
	/// </summary>
	public static Color Aquamarine => new((byte)127, (byte)255, (byte)212);

	/// <summary>
	/// Azure color (R:240, G:255, B:255, A:255).
	/// <para>RGBA Hex: #F0FFFFFF.</para>
	/// </summary>
	public static Color Azure => new((byte)240, (byte)255, (byte)255);

	/// <summary>
	/// Beige color (R:245, G:245, B:220, A:255).
	/// <para>RGBA Hex: #F5F5DCFF.</para>
	/// </summary>
	public static Color Beige => new((byte)245, (byte)245, (byte)220);

	/// <summary>
	/// Bisque color (R:255, G:228, B:196, A:255).
	/// <para>RGBA Hex: #FFE4C4FF.</para>
	/// </summary>
	public static Color Bisque => new((byte)255, (byte)228, (byte)196);

	/// <summary>
	/// Black color (R:0, G:0, B:0, A:255).
	/// <para>RGBA Hex: #000000FF.</para>
	/// </summary>
	public static Color Black => new((byte)0, (byte)0, (byte)0);

	/// <summary>
	/// BlanchedAlmond color (R:255, G:235, B:205, A:255).
	/// <para>RGBA Hex: #FFEBCDFF.</para>
	/// </summary>
	public static Color BlanchedAlmond => new((byte)255, (byte)235, (byte)205);

	/// <summary>
	/// Blue color (R:0, G:0, B:255, A:255).
	/// <para>RGBA Hex: #0000FFFF.</para>
	/// </summary>
	public static Color Blue => new((byte)0, (byte)0, (byte)255);

	/// <summary>
	/// BlueViolet color (R:138, G:43, B:226, A:255).
	/// <para>RGBA Hex: #8A2BE2FF.</para>
	/// </summary>
	public static Color BlueViolet => new((byte)138, (byte)43, (byte)226);

	/// <summary>
	/// Brown color (R:165, G:42, B:42, A:255).
	/// <para>RGBA Hex: #A52A2AFF.</para>
	/// </summary>
	public static Color Brown => new((byte)165, (byte)42, (byte)42);

	/// <summary>
	/// BurlyWood color (R:222, G:184, B:135, A:255).
	/// <para>RGBA Hex: #DEB887FF.</para>
	/// </summary>
	public static Color BurlyWood => new((byte)222, (byte)184, (byte)135);

	/// <summary>
	/// CadetBlue color (R:95, G:158, B:160, A:255).
	/// <para>RGBA Hex: #5F9EA0FF.</para>
	/// </summary>
	public static Color CadetBlue => new((byte)95, (byte)158, (byte)160);

	/// <summary>
	/// Chartreuse color (R:127, G:255, B:0, A:255).
	/// <para>RGBA Hex: #7FFF00FF.</para>
	/// </summary>
	public static Color Chartreuse => new((byte)127, (byte)255, (byte)0);

	/// <summary>
	/// Chocolate color (R:210, G:105, B:30, A:255).
	/// <para>RGBA Hex: #D2691EFF.</para>
	/// </summary>
	public static Color Chocolate => new((byte)210, (byte)105, (byte)30);

	/// <summary>
	/// Coral color (R:255, G:127, B:80, A:255).
	/// <para>RGBA Hex: #FF7F50FF.</para>
	/// </summary>
	public static Color Coral => new((byte)255, (byte)127, (byte)80);

	/// <summary>
	/// CornflowerBlue color (R:100, G:149, B:237, A:255).
	/// <para>RGBA Hex: #6495EDFF.</para>
	/// </summary>
	public static Color CornflowerBlue => new((byte)100, (byte)149, (byte)237);

	/// <summary>
	/// Cornsilk color (R:255, G:248, B:220, A:255).
	/// <para>RGBA Hex: #FFF8DCFF.</para>
	/// </summary>
	public static Color Cornsilk => new((byte)255, (byte)248, (byte)220);

	/// <summary>
	/// Crimson color (R:220, G:20, B:60, A:255).
	/// <para>RGBA Hex: #DC143CFF.</para>
	/// </summary>
	public static Color Crimson => new((byte)220, (byte)20, (byte)60);

	/// <summary>
	/// Cyan color (R:0, G:255, B:255, A:255).
	/// <para>RGBA Hex: #00FFFFFF.</para>
	/// </summary>
	public static Color Cyan => new((byte)0, (byte)255, (byte)255);

	/// <summary>
	/// DarkBlue color (R:0, G:0, B:139, A:255).
	/// <para>RGBA Hex: #00008BFF.</para>
	/// </summary>
	public static Color DarkBlue => new((byte)0, (byte)0, (byte)139);

	/// <summary>
	/// DarkCyan color (R:0, G:139, B:139, A:255).
	/// <para>RGBA Hex: #008B8BFF.</para>
	/// </summary>
	public static Color DarkCyan => new((byte)0, (byte)139, (byte)139);

	/// <summary>
	/// DarkGoldenrod color (R:184, G:134, B:11, A:255).
	/// <para>RGBA Hex: #B8860BFF.</para>
	/// </summary>
	public static Color DarkGoldenrod => new((byte)184, (byte)134, (byte)11);

	/// <summary>
	/// DarkGray color (R:169, G:169, B:169, A:255).
	/// <para>RGBA Hex: #A9A9A9FF.</para>
	/// </summary>
	public static Color DarkGray => new((byte)169, (byte)169, (byte)169);

	/// <summary>
	/// DarkGreen color (R:0, G:100, B:0, A:255).
	/// <para>RGBA Hex: #006400FF.</para>
	/// </summary>
	public static Color DarkGreen => new((byte)0, (byte)100, (byte)0);

	/// <summary>
	/// DarkKhaki color (R:189, G:183, B:107, A:255).
	/// <para>RGBA Hex: #BDB76BFF.</para>
	/// </summary>
	public static Color DarkKhaki => new((byte)189, (byte)183, (byte)107);

	/// <summary>
	/// DarkMagenta color (R:139, G:0, B:139, A:255).
	/// <para>RGBA Hex: #8B008BFF.</para>
	/// </summary>
	public static Color DarkMagenta => new((byte)139, (byte)0, (byte)139);

	/// <summary>
	/// DarkOliveGreen color (R:85, G:107, B:47, A:255).
	/// <para>RGBA Hex: #556B2FFF.</para>
	/// </summary>
	public static Color DarkOliveGreen => new((byte)85, (byte)107, (byte)47);

	/// <summary>
	/// DarkOrange color (R:255, G:140, B:0, A:255).
	/// <para>RGBA Hex: #FF8C00FF.</para>
	/// </summary>
	public static Color DarkOrange => new((byte)255, (byte)140, (byte)0);

	/// <summary>
	/// DarkOrchid color (R:153, G:50, B:204, A:255).
	/// <para>RGBA Hex: #9932CCFF.</para>
	/// </summary>
	public static Color DarkOrchid => new((byte)153, (byte)50, (byte)204);

	/// <summary>
	/// DarkRed color (R:139, G:0, B:0, A:255).
	/// <para>RGBA Hex: #8B0000FF.</para>
	/// </summary>
	public static Color DarkRed => new((byte)139, (byte)0, (byte)0);

	/// <summary>
	/// DarkSalmon color (R:233, G:150, B:122, A:255).
	/// <para>RGBA Hex: #E9967AFF.</para>
	/// </summary>
	public static Color DarkSalmon => new((byte)233, (byte)150, (byte)122);

	/// <summary>
	/// DarkSeaGreen color (R:143, G:188, B:143, A:255).
	/// <para>RGBA Hex: #8FBC8FFF.</para>
	/// </summary>
	public static Color DarkSeaGreen => new((byte)143, (byte)188, (byte)143);

	/// <summary>
	/// DarkSlateBlue color (R:72, G:61, B:139, A:255).
	/// <para>RGBA Hex: #483D8BFF.</para>
	/// </summary>
	public static Color DarkSlateBlue => new((byte)72, (byte)61, (byte)139);

	/// <summary>
	/// DarkSlateGray color (R:47, G:79, B:79, A:255).
	/// <para>RGBA Hex: #2F4F4FFF.</para>
	/// </summary>
	public static Color DarkSlateGray => new((byte)47, (byte)79, (byte)79);

	/// <summary>
	/// DarkTurquoise color (R:0, G:206, B:209, A:255).
	/// <para>RGBA Hex: #00CED1FF.</para>
	/// </summary>
	public static Color DarkTurquoise => new((byte)0, (byte)206, (byte)209);

	/// <summary>
	/// DarkViolet color (R:148, G:0, B:211, A:255).
	/// <para>RGBA Hex: #9400D3FF.</para>
	/// </summary>
	public static Color DarkViolet => new((byte)148, (byte)0, (byte)211);

	/// <summary>
	/// DeepPink color (R:255, G:20, B:147, A:255).
	/// <para>RGBA Hex: #FF1493FF.</para>
	/// </summary>
	public static Color DeepPink => new((byte)255, (byte)20, (byte)147);

	/// <summary>
	/// DeepSkyBlue color (R:0, G:191, B:255, A:255).
	/// <para>RGBA Hex: #00BFFFFF.</para>
	/// </summary>
	public static Color DeepSkyBlue => new((byte)0, (byte)191, (byte)255);

	/// <summary>
	/// DimGray color (R:105, G:105, B:105, A:255).
	/// <para>RGBA Hex: #696969FF.</para>
	/// </summary>
	public static Color DimGray => new((byte)105, (byte)105, (byte)105);

	/// <summary>
	/// DodgerBlue color (R:30, G:144, B:255, A:255).
	/// <para>RGBA Hex: #1E90FFFF.</para>
	/// </summary>
	public static Color DodgerBlue => new((byte)30, (byte)144, (byte)255);

	/// <summary>
	/// Firebrick color (R:178, G:34, B:34, A:255).
	/// <para>RGBA Hex: #B22222FF.</para>
	/// </summary>
	public static Color Firebrick => new((byte)178, (byte)34, (byte)34);

	/// <summary>
	/// FloralWhite color (R:255, G:250, B:240, A:255).
	/// <para>RGBA Hex: #FFFAF0FF.</para>
	/// </summary>
	public static Color FloralWhite => new((byte)255, (byte)250, (byte)240);

	/// <summary>
	/// ForestGreen color (R:34, G:139, B:34, A:255).
	/// <para>RGBA Hex: #228B22FF.</para>
	/// </summary>
	public static Color ForestGreen => new((byte)34, (byte)139, (byte)34);

	/// <summary>
	/// Fuchsia color (R:255, G:0, B:255, A:255).
	/// <para>RGBA Hex: #FF00FFFF.</para>
	/// </summary>
	public static Color Fuchsia => new((byte)255, (byte)0, (byte)255);

	/// <summary>
	/// Gainsboro color (R:220, G:220, B:220, A:255).
	/// <para>RGBA Hex: #DCDCDCFF.</para>
	/// </summary>
	public static Color Gainsboro => new((byte)220, (byte)220, (byte)220);

	/// <summary>
	/// GhostWhite color (R:248, G:248, B:255, A:255).
	/// <para>RGBA Hex: #F8F8FFFF.</para>
	/// </summary>
	public static Color GhostWhite => new((byte)248, (byte)248, (byte)255);

	/// <summary>
	/// Gold color (R:255, G:215, B:0, A:255).
	/// <para>RGBA Hex: #FFD700FF.</para>
	/// </summary>
	public static Color Gold => new((byte)255, (byte)215, (byte)0);

	/// <summary>
	/// Goldenrod color (R:218, G:165, B:32, A:255).
	/// <para>RGBA Hex: #DAA520FF.</para>
	/// </summary>
	public static Color Goldenrod => new((byte)218, (byte)165, (byte)32);

	/// <summary>
	/// Gray color (R:128, G:128, B:128, A:255).
	/// <para>RGBA Hex: #808080FF.</para>
	/// </summary>
	public static Color Gray => new((byte)128, (byte)128, (byte)128);

	/// <summary>
	/// Green color (R:0, G:128, B:0, A:255).
	/// <para>RGBA Hex: #008000FF.</para>
	/// </summary>
	public static Color Green => new((byte)0, (byte)128, (byte)0);

	/// <summary>
	/// GreenYellow color (R:173, G:255, B:47, A:255).
	/// <para>RGBA Hex: #ADFF2FFF.</para>
	/// </summary>
	public static Color GreenYellow => new((byte)173, (byte)255, (byte)47);

	/// <summary>
	/// Honeydew color (R:240, G:255, B:240, A:255).
	/// <para>RGBA Hex: #F0FFF0FF.</para>
	/// </summary>
	public static Color Honeydew => new((byte)240, (byte)255, (byte)240);

	/// <summary>
	/// HotPink color (R:255, G:105, B:180, A:255).
	/// <para>RGBA Hex: #FF69B4FF.</para>
	/// </summary>
	public static Color HotPink => new((byte)255, (byte)105, (byte)180);

	/// <summary>
	/// IndianRed color (R:205, G:92, B:92, A:255).
	/// <para>RGBA Hex: #CD5C5CFF.</para>
	/// </summary>
	public static Color IndianRed => new((byte)205, (byte)92, (byte)92);

	/// <summary>
	/// Indigo color (R:75, G:0, B:130, A:255).
	/// <para>RGBA Hex: #4B0082FF.</para>
	/// </summary>
	public static Color Indigo => new((byte)75, (byte)0, (byte)130);

	/// <summary>
	/// Ivory color (R:255, G:255, B:240, A:255).
	/// <para>RGBA Hex: #FFFFF0FF.</para>
	/// </summary>
	public static Color Ivory => new((byte)255, (byte)255, (byte)240);

	/// <summary>
	/// Khaki color (R:240, G:230, B:140, A:255).
	/// <para>RGBA Hex: #F0E68CFF.</para>
	/// </summary>
	public static Color Khaki => new((byte)240, (byte)230, (byte)140);

	/// <summary>
	/// Lavender color (R:230, G:230, B:250, A:255).
	/// <para>RGBA Hex: #E6E6FAFF.</para>
	/// </summary>
	public static Color Lavender => new((byte)230, (byte)230, (byte)250);

	/// <summary>
	/// LavenderBlush color (R:255, G:240, B:245, A:255).
	/// <para>RGBA Hex: #FFF0F5FF.</para>
	/// </summary>
	public static Color LavenderBlush => new((byte)255, (byte)240, (byte)245);

	/// <summary>
	/// LawnGreen color (R:124, G:252, B:0, A:255).
	/// <para>RGBA Hex: #7CFC00FF.</para>
	/// </summary>
	public static Color LawnGreen => new((byte)124, (byte)252, (byte)0);

	/// <summary>
	/// LemonChiffon color (R:255, G:250, B:205, A:255).
	/// <para>RGBA Hex: #FFFACDFF.</para>
	/// </summary>
	public static Color LemonChiffon => new((byte)255, (byte)250, (byte)205);

	/// <summary>
	/// LightBlue color (R:173, G:216, B:230, A:255).
	/// <para>RGBA Hex: #ADD8E6FF.</para>
	/// </summary>
	public static Color LightBlue => new((byte)173, (byte)216, (byte)230);

	/// <summary>
	/// LightCoral color (R:240, G:128, B:128, A:255).
	/// <para>RGBA Hex: #F08080FF.</para>
	/// </summary>
	public static Color LightCoral => new((byte)240, (byte)128, (byte)128);

	/// <summary>
	/// LightCyan color (R:224, G:255, B:255, A:255).
	/// <para>RGBA Hex: #E0FFFFFF.</para>
	/// </summary>
	public static Color LightCyan => new((byte)224, (byte)255, (byte)255);

	/// <summary>
	/// LightGoldenrodYellow color (R:250, G:250, B:210, A:255).
	/// <para>RGBA Hex: #FAFAD2FF.</para>
	/// </summary>
	public static Color LightGoldenrodYellow => new((byte)250, (byte)250, (byte)210);

	/// <summary>
	/// LightGray color (R:211, G:211, B:211, A:255).
	/// <para>RGBA Hex: #D3D3D3FF.</para>
	/// </summary>
	public static Color LightGray => new((byte)211, (byte)211, (byte)211);

	/// <summary>
	/// LightGreen color (R:144, G:238, B:144, A:255).
	/// <para>RGBA Hex: #90EE90FF.</para>
	/// </summary>
	public static Color LightGreen => new((byte)144, (byte)238, (byte)144);

	/// <summary>
	/// LightPink color (R:255, G:182, B:193, A:255).
	/// <para>RGBA Hex: #FFB6C1FF.</para>
	/// </summary>
	public static Color LightPink => new((byte)255, (byte)182, (byte)193);

	/// <summary>
	/// LightSalmon color (R:255, G:160, B:122, A:255).
	/// <para>RGBA Hex: #FFA07AFF.</para>
	/// </summary>
	public static Color LightSalmon => new((byte)255, (byte)160, (byte)122);

	/// <summary>
	/// LightSeaGreen color (R:32, G:178, B:170, A:255).
	/// <para>RGBA Hex: #20B2AAFF.</para>
	/// </summary>
	public static Color LightSeaGreen => new((byte)32, (byte)178, (byte)170);

	/// <summary>
	/// LightSkyBlue color (R:135, G:206, B:250, A:255).
	/// <para>RGBA Hex: #87CEFAFF.</para>
	/// </summary>
	public static Color LightSkyBlue => new((byte)135, (byte)206, (byte)250);

	/// <summary>
	/// LightSlateGray color (R:119, G:136, B:153, A:255).
	/// <para>RGBA Hex: #778899FF.</para>
	/// </summary>
	public static Color LightSlateGray => new((byte)119, (byte)136, (byte)153);

	/// <summary>
	/// LightSteelBlue color (R:176, G:196, B:222, A:255).
	/// <para>RGBA Hex: #B0C4DEFF.</para>
	/// </summary>
	public static Color LightSteelBlue => new((byte)176, (byte)196, (byte)222);

	/// <summary>
	/// LightYellow color (R:255, G:255, B:224, A:255).
	/// <para>RGBA Hex: #FFFFE0FF.</para>
	/// </summary>
	public static Color LightYellow => new((byte)255, (byte)255, (byte)224);

	/// <summary>
	/// Lime color (R:0, G:255, B:0, A:255).
	/// <para>RGBA Hex: #00FF00FF.</para>
	/// </summary>
	public static Color Lime => new((byte)0, (byte)255, (byte)0);

	/// <summary>
	/// LimeGreen color (R:50, G:205, B:50, A:255).
	/// <para>RGBA Hex: #32CD32FF.</para>
	/// </summary>
	public static Color LimeGreen => new((byte)50, (byte)205, (byte)50);

	/// <summary>
	/// Linen color (R:250, G:240, B:230, A:255).
	/// <para>RGBA Hex: #FAF0E6FF.</para>
	/// </summary>
	public static Color Linen => new((byte)250, (byte)240, (byte)230);

	/// <summary>
	/// Magenta color (R:255, G:0, B:255, A:255).
	/// <para>RGBA Hex: #FF00FFFF.</para>
	/// </summary>
	public static Color Magenta => new((byte)255, (byte)0, (byte)255);

	/// <summary>
	/// Maroon color (R:128, G:0, B:0, A:255).
	/// <para>RGBA Hex: #800000FF.</para>
	/// </summary>
	public static Color Maroon => new((byte)128, (byte)0, (byte)0);

	/// <summary>
	/// MediumAquamarine color (R:102, G:205, B:170, A:255).
	/// <para>RGBA Hex: #66CDAAFF.</para>
	/// </summary>
	public static Color MediumAquamarine => new((byte)102, (byte)205, (byte)170);

	/// <summary>
	/// MediumBlue color (R:0, G:0, B:205, A:255).
	/// <para>RGBA Hex: #0000CDFF.</para>
	/// </summary>
	public static Color MediumBlue => new((byte)0, (byte)0, (byte)205);

	/// <summary>
	/// MediumOrchid color (R:186, G:85, B:211, A:255).
	/// <para>RGBA Hex: #BA55D3FF.</para>
	/// </summary>
	public static Color MediumOrchid => new((byte)186, (byte)85, (byte)211);

	/// <summary>
	/// MediumPurple color (R:147, G:112, B:219, A:255).
	/// <para>RGBA Hex: #9370DBFF.</para>
	/// </summary>
	public static Color MediumPurple => new((byte)147, (byte)112, (byte)219);

	/// <summary>
	/// MediumSeaGreen color (R:60, G:179, B:113, A:255).
	/// <para>RGBA Hex: #3CB371FF.</para>
	/// </summary>
	public static Color MediumSeaGreen => new((byte)60, (byte)179, (byte)113);

	/// <summary>
	/// MediumSlateBlue color (R:123, G:104, B:238, A:255).
	/// <para>RGBA Hex: #7B68EEFF.</para>
	/// </summary>
	public static Color MediumSlateBlue => new((byte)123, (byte)104, (byte)238);

	/// <summary>
	/// MediumSpringGreen color (R:0, G:250, B:154, A:255).
	/// <para>RGBA Hex: #00FA9AFF.</para>
	/// </summary>
	public static Color MediumSpringGreen => new((byte)0, (byte)250, (byte)154);

	/// <summary>
	/// MediumTurquoise color (R:72, G:209, B:204, A:255).
	/// <para>RGBA Hex: #48D1CCFF.</para>
	/// </summary>
	public static Color MediumTurquoise => new((byte)72, (byte)209, (byte)204);

	/// <summary>
	/// MediumVioletRed color (R:199, G:21, B:133, A:255).
	/// <para>RGBA Hex: #C71585FF.</para>
	/// </summary>
	public static Color MediumVioletRed => new((byte)199, (byte)21, (byte)133);

	/// <summary>
	/// MidnightBlue color (R:25, G:25, B:112, A:255).
	/// <para>RGBA Hex: #191970FF.</para>
	/// </summary>
	public static Color MidnightBlue => new((byte)25, (byte)25, (byte)112);

	/// <summary>
	/// MintCream color (R:245, G:255, B:250, A:255).
	/// <para>RGBA Hex: #F5FFFAFF.</para>
	/// </summary>
	public static Color MintCream => new((byte)245, (byte)255, (byte)250);

	/// <summary>
	/// MistyRose color (R:255, G:228, B:225, A:255).
	/// <para>RGBA Hex: #FFE4E1FF.</para>
	/// </summary>
	public static Color MistyRose => new((byte)255, (byte)228, (byte)225);

	/// <summary>
	/// Moccasin color (R:255, G:228, B:181, A:255).
	/// <para>RGBA Hex: #FFE4B5FF.</para>
	/// </summary>
	public static Color Moccasin => new((byte)255, (byte)228, (byte)181);

	/// <summary>
	/// NavajoWhite color (R:255, G:222, B:173, A:255).
	/// <para>RGBA Hex: #FFDEADFF.</para>
	/// </summary>
	public static Color NavajoWhite => new((byte)255, (byte)222, (byte)173);

	/// <summary>
	/// Navy color (R:0, G:0, B:128, A:255).
	/// <para>RGBA Hex: #000080FF.</para>
	/// </summary>
	public static Color Navy => new((byte)0, (byte)0, (byte)128);

	/// <summary>
	/// OldLace color (R:253, G:245, B:230, A:255).
	/// <para>RGBA Hex: #FDF5E6FF.</para>
	/// </summary>
	public static Color OldLace => new((byte)253, (byte)245, (byte)230);

	/// <summary>
	/// Olive color (R:128, G:128, B:0, A:255).
	/// <para>RGBA Hex: #808000FF.</para>
	/// </summary>
	public static Color Olive => new((byte)128, (byte)128, (byte)0);

	/// <summary>
	/// OliveDrab color (R:107, G:142, B:35, A:255).
	/// <para>RGBA Hex: #6B8E23FF.</para>
	/// </summary>
	public static Color OliveDrab => new((byte)107, (byte)142, (byte)35);

	/// <summary>
	/// Orange color (R:255, G:165, B:0, A:255).
	/// <para>RGBA Hex: #FFA500FF.</para>
	/// </summary>
	public static Color Orange => new((byte)255, (byte)165, (byte)0);

	/// <summary>
	/// OrangeRed color (R:255, G:69, B:0, A:255).
	/// <para>RGBA Hex: #FF4500FF.</para>
	/// </summary>
	public static Color OrangeRed => new((byte)255, (byte)69, (byte)0);

	/// <summary>
	/// Orchid color (R:218, G:112, B:214, A:255).
	/// <para>RGBA Hex: #DA70D6FF.</para>
	/// </summary>
	public static Color Orchid => new((byte)218, (byte)112, (byte)214);

	/// <summary>
	/// PaleGoldenrod color (R:238, G:232, B:170, A:255).
	/// <para>RGBA Hex: #EEE8AAFF.</para>
	/// </summary>
	public static Color PaleGoldenrod => new((byte)238, (byte)232, (byte)170);

	/// <summary>
	/// PaleGreen color (R:152, G:251, B:152, A:255).
	/// <para>RGBA Hex: #98FB98FF.</para>
	/// </summary>
	public static Color PaleGreen => new((byte)152, (byte)251, (byte)152);

	/// <summary>
	/// PaleTurquoise color (R:175, G:238, B:238, A:255).
	/// <para>RGBA Hex: #AFEEEEFF.</para>
	/// </summary>
	public static Color PaleTurquoise => new((byte)175, (byte)238, (byte)238);

	/// <summary>
	/// PaleVioletRed color (R:219, G:112, B:147, A:255).
	/// <para>RGBA Hex: #DB7093FF.</para>
	/// </summary>
	public static Color PaleVioletRed => new((byte)219, (byte)112, (byte)147);

	/// <summary>
	/// PapayaWhip color (R:255, G:239, B:213, A:255).
	/// <para>RGBA Hex: #FFEFD5FF.</para>
	/// </summary>
	public static Color PapayaWhip => new((byte)255, (byte)239, (byte)213);

	/// <summary>
	/// PeachPuff color (R:255, G:218, B:185, A:255).
	/// <para>RGBA Hex: #FFDAB9FF.</para>
	/// </summary>
	public static Color PeachPuff => new((byte)255, (byte)218, (byte)185);

	/// <summary>
	/// Peru color (R:205, G:133, B:63, A:255).
	/// <para>RGBA Hex: #CD853FFF.</para>
	/// </summary>
	public static Color Peru => new((byte)205, (byte)133, (byte)63);

	/// <summary>
	/// Pink color (R:255, G:192, B:203, A:255).
	/// <para>RGBA Hex: #FFC0CBFF.</para>
	/// </summary>
	public static Color Pink => new((byte)255, (byte)192, (byte)203);

	/// <summary>
	/// Plum color (R:221, G:160, B:221, A:255).
	/// <para>RGBA Hex: #DDA0DDFF.</para>
	/// </summary>
	public static Color Plum => new((byte)221, (byte)160, (byte)221);

	/// <summary>
	/// PowderBlue color (R:176, G:224, B:230, A:255).
	/// <para>RGBA Hex: #B0E0E6FF.</para>
	/// </summary>
	public static Color PowderBlue => new((byte)176, (byte)224, (byte)230);

	/// <summary>
	/// Purple color (R:128, G:0, B:128, A:255).
	/// <para>RGBA Hex: #800080FF.</para>
	/// </summary>
	public static Color Purple => new((byte)128, (byte)0, (byte)128);

	/// <summary>
	/// Red color (R:255, G:0, B:0, A:255).
	/// <para>RGBA Hex: #FF0000FF.</para>
	/// </summary>
	public static Color Red => new((byte)255, (byte)0, (byte)0);

	/// <summary>
	/// RosyBrown color (R:188, G:143, B:143, A:255).
	/// <para>RGBA Hex: #BC8F8FFF.</para>
	/// </summary>
	public static Color RosyBrown => new((byte)188, (byte)143, (byte)143);

	/// <summary>
	/// RoyalBlue color (R:65, G:105, B:225, A:255).
	/// <para>RGBA Hex: #4169E1FF.</para>
	/// </summary>
	public static Color RoyalBlue => new((byte)65, (byte)105, (byte)225);

	/// <summary>
	/// SaddleBrown color (R:139, G:69, B:19, A:255).
	/// <para>RGBA Hex: #8B4513FF.</para>
	/// </summary>
	public static Color SaddleBrown => new((byte)139, (byte)69, (byte)19);

	/// <summary>
	/// Salmon color (R:250, G:128, B:114, A:255).
	/// <para>RGBA Hex: #FA8072FF.</para>
	/// </summary>
	public static Color Salmon => new((byte)250, (byte)128, (byte)114);

	/// <summary>
	/// SandyBrown color (R:244, G:164, B:96, A:255).
	/// <para>RGBA Hex: #F4A460FF.</para>
	/// </summary>
	public static Color SandyBrown => new((byte)244, (byte)164, (byte)96);

	/// <summary>
	/// SeaGreen color (R:46, G:139, B:87, A:255).
	/// <para>RGBA Hex: #2E8B57FF.</para>
	/// </summary>
	public static Color SeaGreen => new((byte)46, (byte)139, (byte)87);

	/// <summary>
	/// SeaShell color (R:255, G:245, B:238, A:255).
	/// <para>RGBA Hex: #FFF5EEFF.</para>
	/// </summary>
	public static Color SeaShell => new((byte)255, (byte)245, (byte)238);

	/// <summary>
	/// Sienna color (R:160, G:82, B:45, A:255).
	/// <para>RGBA Hex: #A0522DFF.</para>
	/// </summary>
	public static Color Sienna => new((byte)160, (byte)82, (byte)45);

	/// <summary>
	/// Silver color (R:192, G:192, B:192, A:255).
	/// <para>RGBA Hex: #C0C0C0FF.</para>
	/// </summary>
	public static Color Silver => new((byte)192, (byte)192, (byte)192);

	/// <summary>
	/// SkyBlue color (R:135, G:206, B:235, A:255).
	/// <para>RGBA Hex: #87CEEBFF.</para>
	/// </summary>
	public static Color SkyBlue => new((byte)135, (byte)206, (byte)235);

	/// <summary>
	/// SlateBlue color (R:106, G:90, B:205, A:255).
	/// <para>RGBA Hex: #6A5ACDFF.</para>
	/// </summary>
	public static Color SlateBlue => new((byte)106, (byte)90, (byte)205);

	/// <summary>
	/// SlateGray color (R:112, G:128, B:144, A:255).
	/// <para>RGBA Hex: #708090FF.</para>
	/// </summary>
	public static Color SlateGray => new((byte)112, (byte)128, (byte)144);

	/// <summary>
	/// Snow color (R:255, G:250, B:250, A:255).
	/// <para>RGBA Hex: #FFFAFAFF.</para>
	/// </summary>
	public static Color Snow => new((byte)255, (byte)250, (byte)250);

	/// <summary>
	/// SpringGreen color (R:0, G:255, B:127, A:255).
	/// <para>RGBA Hex: #00FF7FFF.</para>
	/// </summary>
	public static Color SpringGreen => new((byte)0, (byte)255, (byte)127);

	/// <summary>
	/// SteelBlue color (R:70, G:130, B:180, A:255).
	/// <para>RGBA Hex: #4682B4FF.</para>
	/// </summary>
	public static Color SteelBlue => new((byte)70, (byte)130, (byte)180);

	/// <summary>
	/// Tan color (R:210, G:180, B:140, A:255).
	/// <para>RGBA Hex: #D2B48CFF.</para>
	/// </summary>
	public static Color Tan => new((byte)210, (byte)180, (byte)140);

	/// <summary>
	/// Teal color (R:0, G:128, B:128, A:255).
	/// <para>RGBA Hex: #008080FF.</para>
	/// </summary>
	public static Color Teal => new((byte)0, (byte)128, (byte)128);

	/// <summary>
	/// Thistle color (R:216, G:191, B:216, A:255).
	/// <para>RGBA Hex: #D8BFD8FF.</para>
	/// </summary>
	public static Color Thistle => new((byte)216, (byte)191, (byte)216);

	/// <summary>
	/// Tomato color (R:255, G:99, B:71, A:255).
	/// <para>RGBA Hex: #FF6347FF.</para>
	/// </summary>
	public static Color Tomato => new((byte)255, (byte)99, (byte)71);

	/// <summary>
	/// Turquoise color (R:64, G:224, B:208, A:255).
	/// <para>RGBA Hex: #40E0D0FF.</para>
	/// </summary>
	public static Color Turquoise => new((byte)64, (byte)224, (byte)208);

	/// <summary>
	/// Violet color (R:238, G:130, B:238, A:255).
	/// <para>RGBA Hex: #EE82EEFF.</para>
	/// </summary>
	public static Color Violet => new((byte)238, (byte)130, (byte)238);

	/// <summary>
	/// Wheat color (R:245, G:222, B:179, A:255).
	/// <para>RGBA Hex: #F5DEB3FF.</para>
	/// </summary>
	public static Color Wheat => new((byte)245, (byte)222, (byte)179);

	/// <summary>
	/// White color (R:255, G:255, B:255, A:255).
	/// <para>RGBA Hex: #FFFFFFFF.</para>
	/// </summary>
	public static Color White => new((byte)255, (byte)255, (byte)255);

	/// <summary>
	/// WhiteSmoke color (R:245, G:245, B:245, A:255).
	/// <para>RGBA Hex: #F5F5F5FF.</para>
	/// </summary>
	public static Color WhiteSmoke => new((byte)245, (byte)245, (byte)245);

	/// <summary>
	/// Yellow color (R:255, G:255, B:0, A:255).
	/// <para>RGBA Hex: #FFFF00FF.</para>
	/// </summary>
	public static Color Yellow => new((byte)255, (byte)255, (byte)0);

	/// <summary>
	/// YellowGreen color (R:154, G:205, B:50, A:255).
	/// <para>RGBA Hex: #9ACD32FF.</para>
	/// </summary>
	public static Color YellowGreen => new((byte)154, (byte)205, (byte)50);

	/// <summary>
	/// RebeccaPurple color (R:102, G:51, B:153, A:255).
	/// <para>RGBA Hex: #663399FF.</para>
	/// </summary>
	public static Color RebeccaPurple => new((byte)102, (byte)51, (byte)153);

#endregion Built-In Colors

}